import type { Metadata } from "next";
import { Geist, Geist_Mono , Audiowide , Archivo } from "next/font/google";
import "./globals.css";
import Navbar from "./components/sub-components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const audioWide = Audiowide({
  variable:"--font-Audiowide",
  subsets:["latin"],
  weight:["400"]
})

const archivo = Archivo({
  variable:"--font-archivo",
  subsets:["latin"],
  weight:["100","200","300","400","500","600","700","800","900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
